---
- name: Define stack_download_url (Linux)
  set_fact:
    stack_download_url: "{{ __stack_base_url }}/stack-{{ stack_version }}-linux-{{ ansible_architecture }}.tar.gz"
  when:
    - ansible_system == 'Linux'
    - stack_download_url is not defined

- name: Download stack
  get_url:
    url: "{{ stack_download_url }}"
    dest: "{{ workspace }}/stack-{{ stack_version }}.tar.gz"

- name: Create directory
  file:
    path: "{{ workspace }}/stack-{{ stack_version }}"
    state: directory

- name: Extract stack
  unarchive:
    src: "{{ workspace }}/stack-{{ stack_version }}.tar.gz"
    dest: "{{ workspace }}/stack-{{ stack_version }}/"
    mode: 0755
    remote_src: true
    extra_opts:
      - --strip-components=1

- name: Copy binary
  copy:
    src: "{{ workspace }}/stack-{{ stack_version }}/stack"
    dest: "{{ stack_install_dir }}/stack"
    mode: 0755
    remote_src: true
