---
- name: Update APT cache
  apt:
    update_cache: true
    cache_valid_time: 86400

- name: Install dependencies
  apt:
    name: "{{ haskell_stack_dependencies }}"
    state: present

- name: Download and extract stack
  unarchive:
    src: "https://github.com/commercialhaskell/stack/releases/download/v{{ haskell_stack_version }}/{{ haskell_stack_name }}.tar.gz"
    dest: "{{ workspace }}"
    copy: false

- name: Copy binary
  copy:
    src: "{{ workspace }}/{{ haskell_stack_name }}/stack"
    dest: "{{ haskell_stack_bin_dir }}"
    mode: 0755
    remote_src: true
  when: haskell_stack_copy_bin | bool
