---
- name: haskell-stack | Install dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - g++
    - gcc
    - git
    - gnupg
    - libc6-dev
    - libffi-dev
    - libgmp-dev
    - make
    - xz-utils
    - zlib1g-dev

- name: haskell-stack | Create temp directory
  tempfile:
    suffix: haskell-stack
    state: directory
  register: temp

- name: haskell-stack | Download stack
  get_url:
    url: "https://www.stackage.org/stack/linux-x86_64"
    dest: "{{ temp.path }}/stack.tar.gz"

- name: haskell-stack | Extract stack
  unarchive:
    src: "{{ temp.path }}/stack.tar.gz"
    dest: "{{ temp.path }}"
    remote_src: yes
    extra_opts:
      - "--strip-components=1"

- name: haskell-stack | Copy binary
  copy:
    src: "{{ temp.path }}/stack"
    dest: "/usr/local/bin"
    mode: 0755
    remote_src: yes

- name: haskell-stack | Remove tempfile directory
  file:
    path: "{{ temp.path }}"
    state: absent

- name: haskell-stack | Create global directory
  file:
    path: "{{ ansible_user_dir }}/.stack/global-project"
    state: directory

- name: haskell-stack | Copy global stack.yaml
  template:
    src: stack.yaml.j2
    dest: "{{ ansible_user_dir }}/.stack/global-project/stack.yaml"
