---
- name: Update cache
  apt:
    update_cache: true
    cache_valid_time: 86400

- name: Install dependencies
  apt:
    name: "{{ haskell_stack_dependencies }}"
    state: present

- name: Download stack
  get_url:
    url: "https://github.com/commercialhaskell/stack/releases/download/v{{ haskell_stack_version }}/{{ haskell_stack_name }}.tar.gz"
    dest: "{{ workspace }}/stack-{{ haskell_stack_version }}.tar.gz"

- name: Create directory
  file:
    path: "{{ workspace }}/stack-{{ haskell_stack_version }}"
    state: directory

- name: Extract stack
  unarchive:
    src: "{{ workspace }}/stack-{{ haskell_stack_version }}.tar.gz"
    dest: "{{ workspace }}/stack-{{ haskell_stack_version }}"
    remote_src: true
    extra_opts:
      - --strip-components=1

- name: Copy binary
  copy:
    src: "{{ workspace }}/stack-{{ haskell_stack_version }}/stack"
    dest: "{{ haskell_stack_bin_dir }}"
    mode: 0755
    remote_src: true
  when: haskell_stack_copy_bin | bool
